PROJECT=microsupport
PROJECT_NAME=microsupport
PROJECT_VERSION=20120227
PROJECT_EMAIL=jeffk@meyersound.com
PROJECT_LICENSE=private
PROJECT_MAINTAINER=jeffk@meyersound.com
PROJECT_COPYRIGHT=Copyright 2012
PROJECT_DESCRIPTION=microsupport
PROJECT_WEBSITE=https://github.com/jeffk-meyersound/microsupport
PROJECT_IDENTIFIER=com.meyersound.microsupport
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
COMPILE_FLAGS+=-Wall -Wunused 
CFLAGS+=-std=c99

ENABLE_PRECOMPILED_HEADERS?=1
PRECOMPILED_HEADER=$(TOP)/include/us_world.h

STRIP=true

ifdef US_ENABLE_RAW_ETHERNET
DEFINES+=US_ENABLE_RAW_ETHERNET=$(US_ENABLE_RAW_ETHERNET)
endif

ifdef US_ENABLE_PCAP
DEFINES+=US_ENABLE_PCAP=$(US_ENABLE_PCAP)
LDLIBS+=-lpcap
endif


